export const cities = [
  "Muston",
  "Tadmaton",
  "Monk Hesleden",
  "Bath",
  "Crewe",
  "Tamworth",
  "Burnley",
  "Arundel",
  "Winton",
  "Wasperton",
  "Dalbeattie",
  "Billingham",
  "Old Buckenham",
  "Worthing",
  "Chetton",
  "Carnoustie",
  "Selby",
  "Cotherstone",
  "Briston",
  "Heslington",
  "Middlewich",
  "Liskeard",
  "Great and Little Broughton",
  "Radford Semele",
  "Brownhills",
  "Driffield",
  "Aldridge",
  "Attleborough",
  "Trimdon",
  "Shanklin",
  "Kirkcudbright",
  "Chinnor",
  "Stanhope",
  "Ripley",
  "Hutton Henry",
  "Perranporth",
  "Rawtenstall",
  "Warwick",
  "Sidlesham",
  "Stainton",
  "Holt",
  "Lcp Stanhope and Wolsingham Parishes And",
  "Walsingham",
  "Sowerby",
  "West Bromwich",
  "Cuddesdon",
  "Insch",
  "Darwen",
  "Middleton Cheney",
  "Bidford-on-Avon",
  "Wells-next-the-Sea",
  "Kidlington",
  "Durham",
  "Mistley",
  "Great Aycliffe",
  "Ightenhill",
  "Atherstone",
  "Westham",
  "Salterforth",
  "Layer Breton",
  "Upper Poppleton",
  "Turriff",
  "Little Clacton",
  "Copmanthorpe",
  "South Petherwin",
  "Fordham",
  "Milltimber",
  "Ventnor",
  "Alpington",
  "Freshwater",
  "Redditch",
  "Shoreham-by-Sea",
  "Staines",
  "Toab",
  "Yafforth",
  "Plymstock",
  "Hatfield",
  "Shipston-on-Stour",
  "Wickham",
  "Bromsgrove",
  "Hempnall",
  "Castle Cary",
  "Templecombe",
  "Eastbourne",
  "Culham",
  "Hounslow",
  "Wincanton",
  "Swanton Morley",
  "Hermitage",
  "Annan",
  "Hailsham",
  "Bingley",
  "Aberdeen",
  "Frinton and Walton",
  "Loftus",
  "Stratford-Upon-Avon",
  "Egham",
  "Steeton",
  "Seaford",
  "Elmstead",
  "Steyning",
  "Lancing",
  "Sound",
  "Southall",
  "Dewsbury",
  "Inverurie",
  "Alfreton",
  "Wombourne",
  "Denham Green",
  "Totland",
  "Long Man",
  "Lewes",
  "Croydon",
  "St Agnes",
  "Keighley",
  "Aberdeen Airport",
  "Banbury",
  "Hutton Mulgrave",
  "Ilkeston",
  "Looe",
  "Rawcliffe",
  "Kirklevington",
  "Sandbach",
  "Wheldrake",
  "Swadlincote",
  "Ladbroke",
  "Kinlochleven",
  "Clitheroe",
  "Saltash",
  "Ealing",
  "Accrington",
  "Settrington",
  "Spennithorne",
  "Clayton",
  "Skelton",
  "Watlington",
  "Yealmpton",
  "Chester-le-Street",
  "Canterbury",
  "Peterculter",
  "Bridge of Don",
  "Kenwyn",
  "Birchwood",
  "Bridgemere",
  "Knutsford",
  "Westhill",
  "Calstock",
  "Nantwich",
  "Harwich",
  "Guisborough",
  "Peterhead",
  "Wymondham",
  "Aldwick",
  "Great Yarmouth",
  "Gretna",
  "Overseal",
  "Southwick",
  "Hurst Green",
  "Bicester",
  "Henfield",
  "Hawkes End",
  "Marske",
  "Kenilworth",
  "Laurencekirk",
  "Great Wyrley",
  "Newchurch",
  "Bilbrook",
  "St Columb Major",
  "Queensbury",
  "Holmes Chapel",
  "Langcliffe",
  "Lifton",
  "Congleton",
  "Glencoe",
  "Snainton",
  "Upton",
  "Woodstock",
  "Callington",
  "Albrighton",
  "Cromer",
  "Newtimber",
  "Rustington",
  "Welwyn",
  "Lymm",
  "Yarmouth",
  "Felpham",
  "Harpenden",
  "Carterton",
  "Croft",
  "Branston",
  "Colburn",
  "Witney",
  "Thorlby",
  "Scarning",
  "Ferryhill",
  "Littlehampton",
  "Swanage",
  "Egglescliffe",
  "Sedgefield",
  "Studley",
  "Winsford",
  "Weaverham",
  "Bickenhill",
  "Bexley",
  "Colehill",
  "Clacton-on-Sea",
  "Saltburn Marske and New Marske",
  "Tavistock",
  "Isle of Canna",
  "Newhaven",
  "Bromley",
  "Heanor",
  "Wareham",
  "Stainton Dale",
  "Crayford",
  "Everton",
  "Bridgnorth",
  "Fakenham",
  "Havant",
  "Sible Hedingham",
  "Burntwood",
  "Spennymoor",
  "Banchory",
  "Thornaby",
  "Wednesfield",
  "Halnaby Ave",
  "Pickering",
  "Burton",
  "Ringmer",
  "Scarborough",
  "Chesterton",
  "Bridlington",
  "Colan",
  "Bures Hamlet",
  "Alford",
  "Trindon",
  "Fringford",
  "Muthill",
  "Lockington",
  "Newquay",
  "Houghton-le-Spring",
  "Thornton-le-Clay",
  "Crieff",
  "North Lodge",
  "Eynsham",
  "Redcar",
  "Holton",
  "Abbots Langley",
  "Burton upon Trent",
  "Chelmsley Wood"
];
