export const professions = [
  "Golfer",
  "Business Consultant",
  "Steward",
  "Lighting Technician",
  "Stage Mover",
  "Analyst",
  "Remedial Therapist",
  "Sales Administrator",
  "Theatre Technician",
  "Lawyer",
  "Trading Standards",
  "Screen Printer",
  "Statistician",
  "Property Dealer",
  "Mechanic",
  "Cleaner",
  "Landlady",
  "Line Manager",
  "Waitress",
  "Line Worker",
  "Probation Worker",
  "Housing Assistant",
  "Printer",
  "Publican",
  "Land Surveyor",
  "Traffic Warden",
  "Sales Executive",
  "Riveter",
  "Ambulance Controller",
  "Hygienist",
  "Purchase Clerk",
  "Bakery Operator",
  "Claims Adjustor",
  "Arborist",
  "Trainee Manager",
  "Massage Therapist",
  "Chef",
  "Promoter",
  "Tax Inspector",
  "Lumberjack",
  "Money Broker",
  "Arbitrator",
  "Accounts Clerk",
  "Bricklayer",
  "Geophysicist",
  "Land Agent",
  "Merchant Seaman",
  "Telegraphist",
  "Train Driver",
  "Proof Reader",
  "Stockbroker",
  "Artist",
  "Training Officer",
  "Garda",
  "Psychiatrist",
  "Art Dealer",
  "Materials Manager",
  "Tax Assistant",
  "Sculptor",
  "Bursar",
  "Claims Assessor",
  "Landlord",
  "Horse Breeder",
  "Project Worker",
  "Home Economist",
  "Premises Security",
  "Househusband",
  "Bus Conductor",
  "Marketing Director",
  "General Practitioner",
  "Wages Clerk",
  "Homeopath",
  "Stage Director",
  "Air Traffic Controller",
  "Garage Manager",
  "Window Dresser",
  "Property Developer",
  "Underwriter",
  "Homecare Manager",
  "Print Finisher",
  "Press Officer",
  "Butchery Manager",
  "Taxi Controller",
  "Landworker",
  "Private Investigator",
  "Bookmaker",
  "Probation Officer",
  "Negotiator",
  "Training Instructor",
  "Steel Worker",
  "Geologist",
  "Telemarketeer",
  "Landowner",
  "Metal Dealer",
  "Vehicle Engineer",
  "Lampshade Maker",
  "Hypnotist",
  "Breeder",
  "Scientist",
  "Nurseryman",
  "Attendant",
  "Analytical Chemist",
  "Gynaecologist",
  "Tutor",
  "Homeworker",
  "Building Advisor",
  "Anaesthetist",
  "Chandler",
  "Master Mariner",
  "Bill Poster",
  "Representative",
  "Station Manager",
  "Leaflet Distributor",
  "Stock Controller",
  "Welfare Assistant",
  "Auditor",
  "Postmaster",
  "Adjustor",
  "Steel Erector",
  "Radio Engineer",
  "Property Buyer",
  "Relocation Agent",
  "Mining Consultant",
  "Vehicle Body Worker",
  "Postwoman",
  "Technician",
  "Training Co-ordinator",
  "Accounts Manager",
  "Bank Manager",
  "Minibus Driver",
  "Health Care Assistant",
  "Hypnotherapist",
  "Thermal Insulator",
  "Production Hand",
  "Tax Manager",
  "Ambulance Crew",
  "Airport Manager",
  "Service Engineer",
  "Ticket Inspector",
  "Timber Inspector",
  "Projectionist",
  "Welfare Rights Officer",
  "Tax Officer",
  "Technical Manager",
  "Tennis Coach",
  "Public House Manager",
  "Rigger",
  "Animal Breeder",
  "Prison Chaplain",
  "Temperature Time",
  "Postman",
  "Preacher",
  "Project Leader",
  "Mooring Contractor",
  "Architect",
  "Laundry Staff",
  "Museum Assistant",
  "Baker",
  "Building Inspector",
  "Lighting Designer",
  "China Restorer",
  "Literary Editor",
  "Potter",
  "Nursing Auxiliary",
  "Clergyman",
  "Progress Chaser",
  "Prison Officer",
  "Hotelier",
  "Practice Manager",
  "Horse Dealer",
  "Transcriber",
  "Production Manager",
  "Quality Manager",
  "Textile Consultant",
  "Word Processing Operator",
  "Property Valuer",
  "Training Assistant",
  "Machinist",
  "Warden",
  "Polisher",
  "Professional Wrestler",
  "Area Manager",
  "Administration Assistant",
  "Production Planner",
  "Lift Engineer",
  "Professional Racing",
  "Pools Collector",
  "Archaeologist",
  "Garage Foreman",
  "Tobacconist",
  "Claims Manager",
  "Actor",
  "Meat Inspector",
  "Almoner",
  "Project Co-ordinator",
  "Biochemist",
  "Accounts Staff",
  "Trinity House Pilot",
  "Chiropodist",
  "Garage Attendant",
  "Psychologist",
  "Training Consultant",
  "Lighterman",
  "Chemist",
  "Translator",
  "Machine Operator",
  "Marketing Agent",
  "Textile Engineer",
  "Matron",
  "Audit Manager",
  "Microbiologist",
  "Vicar",
  "Housewife",
  "Cinema Manager",
  "Merchant Banker",
  "Lighthouse Keeper",
  "Law Clerk",
  "Music Teacher",
  "Local Government",
  "Property Manager",
  "Moneylender",
  "Magician",
  "Refuse Collector",
  "Pool Attendant",
  "Project Engineer",
  "Materials Controller",
  "Locum Pharmacist",
  "Artexer",
  "Nuclear Scientist",
  "Accountant",
  "Post Sorter",
  "Ticket Agent",
  "Meat Wholesaler",
  "Litigation Manager",
  "Medical Supplier",
  "Messenger",
  "Procurator Fiscal",
  "Housing Officer",
  "Lawn Mower",
  "Audiologist",
  "Acoustic Engineer",
  "Lime Kiln Attendant",
  "Gaming Club Manager",
  "Proprietor",
  "Motor Trader",
  "Shepherd",
  "Progress Clerk",
  "Lithographer",
  "Lineman",
  "Baptist Minister"
];
